### ISSUE TITLE
FlipView setState is called after dispose

### ISSUE THREAD

**Issue by shaxxx** [WosLovesLife/flutter_flip_view#1]
In certain conditions FlipView causes exception 
> setState() called after dispose()

which is thrown two times when I flip the card.
Details in the screenshot
![1](https://user-images.githubusercontent.com/1778875/60341097-b06f8000-99ad-11e9-9daf-b2e7ad9cafe3.png)

In my case AnimateList has multiple flip items, being rebuild multiple times.
Sometimes items are build as flipviews, sometimes not.
Exception occurs when Flipview is removed from view.

When this.mounted check is applied no exception is thrown.
Thanks for the widget!

**Comment by WosLovesLife** [comment]
Thank you for your report and I've reviewed your RP, It's nice. I'll merge it and later release a new version
